### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by MMGSN** [dami-pie/app#2]
Criar a Interface - Glauco

**Comment by MMGSN** [comment]
- [x] Entender os objetivos da ferramenta (planejamento)
- [x] Wireframe (esqueleto das telas)
- [x] Refinar a interface
- [x] Validação da Equipe

**Comment by GlaucoCartaxo** [comment]
Devido a probelmas pessoais acabei atrasando a realização do refino da interface que estava programado para ser entregue sexta, mas será entregue na teça dia 06/06.
